# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
#title:          Tale
title:          "Blog for K"
paginate:       5
baseurl:
#url:            "https://chesterhow.github.io"
url:            "https://blog4k.github.io"


# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
#  name:         Chester How
#  url:          http://chester.how
#  email:        chesterhow@gmail.com
  name:         blog4k
  url:          https://blog4k.github.io

# Custom vars
version:        3.4.1
#github:
#  repo:         https://github.com/chesterhow/tale

# Gems
plugins_dir:
  - jekyll-paginate
